spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:userdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

kakao:
  key: {INPUT-YOUR-API-KEY}
  maxPage: 45
  maxSize: 15
naver:
  client-id: {INPUT-YOUR-API-KEY}
  client-secret: {INPUT-YOUR-API-KEY}
  maxPage: 1
  maxSize: 5

hystrix:
  dashboard:
    proxy-stream-allow-list: '*'
management:
  endpoints:
    web:
      exposure:
        include: '*'